### ISSUE TITLE
Cannot retrieve data...

### ISSUE THREAD

**Issue by agademer** [skorokithakis/gweet#2]
Firstly, thanks for sharing your code :)

Install : After upgrading to go > 1.7 and setting GOPATH everything worked fine
```
export GOPATH=~/gocode
go get -v -u github.com/skorokithakis/gweet
go build github.com/skorokithakis/gweet
```

I also managed to push data (or so it seems) :+1: 
`curl --header "Content-Type: application/json"   --request POST   --data '{"username":"xyz","password":"xyz"}'   http://localhost:9835/push/toto/`
return 
`{"message":{"created":"2018-10-28T06:44:47.25748217-04:00","name":"test","values":{}},"status":"success"}`

But impossible to SEE the data :
`curl http://localhost:9835/stream/toto/`
return 
`{"messages":[]}`
(Same in the navigator)

What am I doing wrong ?

Also, side question : Where is the data stored ? Is it persistent between two gweet launch (if I reboot the server).

Thanks again for your work (and I hope... for your help)

Regards,

Antoine

For debug purpose : the log from the server side :
```
./gweet -debug
INFO: 2018/10/28 11:38:22 Listening on 0.0.0.0:9835
INFO: 2018/10/28 11:38:38 127.0.0.1:57630 POST /push/toto/ (156.108µs)
INFO: 2018/10/28 11:39:03 Hashed toto to 31f7a65e315586ac198bd798b6629ce4903d0899476d5741a9f32e2e521b6a66
INFO: 2018/10/28 11:39:03 127.0.0.1:57642 GET /stream/toto/ (105.564µs)
INFO: 2018/10/28 11:45:26 Hashed toto to 31f7a65e315586ac198bd798b6629ce4903d0899476d5741a9f32e2e521b6a66
INFO: 2018/10/28 11:45:26 127.0.0.1:57712 GET /stream/toto/ (114.708µs)
```

**Comment by skorokithakis** [comment]
Hello! That's very odd, I will try it out and see (the program is fairly simple, if you want to try debugging). The data is only stored in memory, so it doesn't survive server reboots, I'm afraid.

**Comment by agademer** [comment]
I had the same problem with you demo site :

curl --header "Content-Type: application/json"   --request POST   --data
'{"username":"xyz","password":"xyz"}'   https://queue.stavros.io/push/test/
{"message":{"created":"2018-10-29T11:58:09.393715258-04:00","name":"test","valus":{}},"status":"success"}

curl https://queue.stavros.io/stream/test/
{"messages":[]}

So it could be fairly easy to test from your side :)
I'm not familiar with go, so even if I understand the general structure of
you algorithm, I was not able to debug the program itself (but I tried
first).

Would it be hard to add so time of persistance ? (Again, I'm not familiar
with go, but I'm am with C/C++/Java)
I could reprogram everything, but the idea was gaining some time with some
clean and well-made program made by you :p

Regards,

Antoine

**Comment by skorokithakis** [comment]
Oh, right. It's not JSON:

```
curl --request POST --data "username=x&password=y" https://gweet.stavros.io/stream/test/
```

**Comment by agademer** [comment]
Thanks !

Best regards,

Antoine
